// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcc2R7ns6_k22pAboSR2yYckgNjTDAKEQ',
    appId: '1:1013266574607:web:800004b2f5fba86351227a',
    messagingSenderId: '1013266574607',
    projectId: 'crypto-list-app-f5198',
    authDomain: 'crypto-list-app-f5198.firebaseapp.com',
    storageBucket: 'crypto-list-app-f5198.appspot.com',
    measurementId: 'G-D6W10EH6W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDm5z3HDCDSw9w2m9sDDeKS3Bkm2pk-Xw',
    appId: '1:1013266574607:android:e660f5a252561d2451227a',
    messagingSenderId: '1013266574607',
    projectId: 'crypto-list-app-f5198',
    storageBucket: 'crypto-list-app-f5198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9R4fwjuyHBiPs9lU2C4BMNymB7EluVE8',
    appId: '1:1013266574607:ios:2a4d96dc3f5712c451227a',
    messagingSenderId: '1013266574607',
    projectId: 'crypto-list-app-f5198',
    storageBucket: 'crypto-list-app-f5198.appspot.com',
    iosBundleId: 'com.example.bitcoin',
  );
}
